### ISSUE TITLE
Error when checking for expired posts.

### ISSUE THREAD

**Issue by jacksaturn** [jsetton/craigslist-renew#16]
I have successfully used the script for a few days, however I receive an error message when I attempt to execute it using the --expired variable. The error message is as follows:

ERROR Something went wrong: 'str' object has no attribute 'get'

The postings parameters are set in my config.yml file.

**Comment by jsetton** [comment]
It is most likely you don't have the correct format for your postings in your `config,yml` file.

It needs to follow this format:

```yaml
postings:
  - title: My post
    area: nyc
  - title: Another post
    area: nyc
```
